import Head from "next/head";
import Hero from "../components/Hero";
import Layout from "../components/Layout";
import Serivices from "../components/Serives";
import Menu from "../components/Menu";
import css from "../styles/Home.module.css"
import {client} from "../lib/client"



export default function Home ({pizzas}) {

  return (
    <Layout>

      <div className={css.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
         <Hero/> 
         <Serivices/>  
         <Menu pizzas={pizzas}/>
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async () =>{
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);
  console.log('query',pizzas)
  
  return{
    props:{
      pizzas
    }
  }
}

